version: '3.8'

services:


  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: fooddilivery
      POSTGRES_USER: daiming
      POSTGRES_PASSWORD: secret
      TZ: UTC
    volumes:
      - fooddilivery-pg-local:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  fooddilivery-pg-local: